name = "musical_scale"
description = "Rosetta Code task to generate musical scale of C"
version = "0.1.0-dev"

authors = ["Stephen Merrony"]
maintainers = ["Stephen Merrony <merrony@gmail.com>"]
maintainers-logins = ["SMerrony"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["musical_scale"]

[build-switches]
# "*".style_checks = ["-gnaty-m"]