name = "anagram_generator"
description = "Anagram Generator task for Rosetta Code"
version = "0.1.0-dev"

authors = ["Stephen Merrony"]
maintainers = ["Stephen Merrony <merrony@gmail.com>"]
maintainers-logins = ["SMerrony"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["anagram_generator"]

[build-switches]
development.style_checks = ["-gnaty-m"]
release.style_checks = "No"